import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Providers";
import ShoppingCartModal from "./components/ShoppingCartModel";
import { NextAuthProvider } from "./components/AuthProvider";
import Toast from "./components/Toast";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BD.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-fit`}>
        <NextAuthProvider>
          <CartProvider>
            <Toast />
            <Navbar />
            <ShoppingCartModal />
            {children}
            <Footer/>
          </CartProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
